#!/usr/bin/env python3
import os
import re
from datetime import datetime
import email.utils

# Configuration
BASE_URL = "https://arosselet.github.io/tamil-tutor"
AUDIO_DIR = "audio"
SCRIPTS_DIR = "content/scripts"
RSS_FILE = "rss.xml"

RSS_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" 
    xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" 
    xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>Tamil Tutor: Mission Lessons</title>
    <link>{base_url}</link>
    <language>en-us</language>
    <itunes:author>Tamil Tutor</itunes:author>
    <itunes:summary>Interactive Tamil language learning sessions.</itunes:summary>
    <description>Interactive Tamil language learning sessions generated by AI.</description>
    <itunes:owner>
      <itunes:name>Tamil Tutor</itunes:name>
    </itunes:owner>
    <itunes:explicit>no</itunes:explicit>
    <itunes:category text="Education">
      <itunes:category text="Language Courses"/>
    </itunes:category>
    <itunes:image href="{base_url}/logo.png"/>
    {items}
  </channel>
</rss>
"""

ITEM_TEMPLATE = """
    <item>
      <title>{title}</title>
      <itunes:author>Tamil Tutor</itunes:author>
      <itunes:summary>{summary}</itunes:summary>
      <enclosure url="{audio_url}" length="{size}" type="audio/mpeg"/>
      <guid>{audio_url}</guid>
      <pubDate>{pub_date}</pubDate>
      <itunes:duration>{duration}</itunes:duration>
    </item>
"""

def get_title_from_md(md_path):
    if not os.path.exists(md_path):
        return None
    with open(md_path, 'r') as f:
        first_line = f.readline().strip()
        if first_line.startswith('#'):
            return first_line.lstrip('#').strip()
    return os.path.basename(md_path)

def generate_rss():
    items = []
    # Get all mp3 files in audio/
    audio_files = [f for f in os.listdir(AUDIO_DIR) if f.endswith('.mp3')]
    # Sort by modification time to keep them somewhat chronological
    audio_files.sort(key=lambda x: os.path.getmtime(os.path.join(AUDIO_DIR, x)), reverse=True)

    for filename in audio_files:
        # Whitelist: Only actual lessons start with 'level' or 'tier'
        if not (filename.startswith('level') or filename.startswith('tier')):
            continue
            
        audio_path = os.path.join(AUDIO_DIR, filename)
        # Try to find matching script
        script_name = filename.replace('.mp3', '.md')
        script_path = os.path.join(SCRIPTS_DIR, script_name)
        
        title = get_title_from_md(script_path) or filename
        size = os.path.getsize(audio_path)
        mtime = os.path.getmtime(audio_path)
        pub_date = email.utils.formatdate(mtime, localtime=True)
        audio_url = f"{BASE_URL}/{AUDIO_DIR}/{filename}"
        
        # Duration is hard to get without external libs, so we'll omit or put dummy
        items.append(ITEM_TEMPLATE.format(
            title=title,
            summary=f"Lesson: {title}",
            audio_url=audio_url,
            size=size,
            pub_date=pub_date,
            duration="00:05:00" # Placeholder
        ))

    rss_content = RSS_TEMPLATE.format(
        base_url=BASE_URL,
        items="".join(items)
    )

    with open(RSS_FILE, 'w') as f:
        f.write(rss_content)
    print(f"✅ Generated {RSS_FILE} with {len(items)} episodes.")

if __name__ == "__main__":
    generate_rss()
